apiVersion: v1
kind: Service
metadata:
  name: imagepolicywebhook
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}  # Uses the clusterIP from values.yaml
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: image-policy-webhook
